# Generated by Django 5.1.6 on 2025-08-09 15:18

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Nmae')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'In-Person Customer',
                'verbose_name_plural': 'In-Person Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('backend', 'BackEnd'), ('frontend', 'FrontEnd'), ('admin', 'Admin'), ('premium', 'Premium'), ('user', 'User')], default='user', max_length=10, verbose_name='User Type')),
                ('is_active', models.BooleanField(default=False, verbose_name='Being Active')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Being Premium')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Being Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Being Superuser')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=70.0, max_digits=10, verbose_name='Amount Payable')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID')),
                ('is_sucessful', models.BooleanField(default=False, verbose_name='Is Successful')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'indexes': [models.Index(fields=['user'], name='users_payme_user_id_f4ee05_idx'), models.Index(fields=['payment_id'], name='users_payme_payment_0485c0_idx'), models.Index(fields=['payment_date'], name='users_payme_payment_ae0757_idx')],
            },
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PremiumSubscription_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'PremiumSubscription',
                'verbose_name_plural': 'PremiumSubscriptions',
                'indexes': [models.Index(fields=['user'], name='users_premi_user_id_ed367b_idx'), models.Index(fields=['start_date'], name='users_premi_start_d_f414cc_idx'), models.Index(fields=['expiry_date'], name='users_premi_expiry__3f2f58_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10, verbose_name='Gender')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to, verbose_name='Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
                'indexes': [models.Index(fields=['user'], name='users_userp_user_id_d181df_idx'), models.Index(fields=['phone'], name='users_userp_phone_ed0c08_idx'), models.Index(fields=['gender'], name='users_userp_gender_945cf0_idx')],
            },
        ),
    ]
