# Generated by Django 5.1.6 on 2025-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='users_payme_payment_e0854e_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_sucessful',
            field=models.BooleanField(default=False, verbose_name='Is Successful'),
        ),
    ]
