# Generated by Django 5.1.6 on 2025-10-04 10:51

import config.storages
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=config.storages.ArvanCloudStorage(), upload_to=users.models.upload_to, verbose_name='Picture'),
        ),
    ]
