# Generated by Django 5.1.6 on 2025-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_sucessful',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='IRT', max_length=10, verbose_name='Currency'),
        ),
    ]
