# Generated by Django 5.1.6 on 2025-10-04 10:51

import config.storages
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('processed', 'در-حال-پردازش')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storages.ArvanCloudStorage(), upload_to=main.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'در-انتظار-ارسال'), ('shipped', 'ارسال-شده'), ('delivered', 'تحویل-شده')], default='pending', max_length=20, verbose_name='Status Delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='delivery_method',
            field=models.CharField(choices=[('normal', 'ارسال-عادی'), ('fast', 'ارسال-سریع'), ('postal', 'پست')], max_length=20, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(storage=config.storages.ArvanCloudStorage(), upload_to=main.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], max_length=10, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('credit_card', 'کارت-بانکی'), ('online', 'درگاه')], max_length=15, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('waiting', 'در-انتظار-پرداخت'), ('successful', 'پرداخت-موفق'), ('failed', 'پرداخت-ناموفق'), ('shipped', 'ارسال-شده'), ('completed', 'سفارش-تکمیل-شده'), ('canceled', 'سفارش-لغو-شده'), ('refunded', 'بازپرداخت-شده')], default='on_hold', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storages.ArvanCloudStorage(), upload_to=main.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('processed', 'در-حال-پردازش'), ('abandoned', 'لغو-شده')], default='active', max_length=10, verbose_name='Cart Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('input', 'ورپدی'), ('output', 'خروجی'), ('defective', 'مرجوعی'), ('sent_back', 'مرجوع-شده')], default='input', max_length=10, verbose_name='Warehouse Type'),
        ),
    ]
