# Generated by Django 5.1.6 on 2025-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_applied',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_hold', 'در-انتظار'), ('waiting', 'در-انتظار-پرداخت'), ('successful', 'پرداخت-موفق'), ('failed', 'پرداخت-ناموفق'), ('shipped', 'ارسال-شده'), ('completed', 'سفارش-تکمیل-شده'), ('canceled', 'سفارش-لغو-شده'), ('refunded', 'بازپرداخت-شده')], default='on_hold', max_length=20, verbose_name='Status'),
        ),
    ]
