# Generated by Django 5.1.6 on 2025-11-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_order_number'),
        ('users', '0003_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('method', models.CharField(choices=[('wallet', 'کیف-پول'), ('bank', 'انتقال-بانکی')], default='wallet', max_length=20, verbose_name='Method')),
                ('status', models.CharField(choices=[('requested', 'درخواست-شده'), ('approved', 'تایید-شده'), ('completed', 'تکمیل-شده')], default='requested', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
            },
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='main_transa_payment_e3dd0a_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('deposit', 'واریز'), ('payment', 'پرداخت'), ('refund', 'بازپرداخت')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='users.wallet', verbose_name='Wallet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_hold', 'در-انتظار-ثبت'), ('waiting', 'در-انتظار-پرداخت'), ('successful', 'پرداخت-موفق'), ('failed', 'پرداخت-ناموفق'), ('shipped', 'ارسال-شده'), ('completed', 'سفارش-تکمیل-شده'), ('canceled', 'سفارش-لغو-شده'), ('refunded', 'بازپرداخت-شده')], default='on_hold', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='main_transa_referen_f343d8_idx'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refund_order', to='main.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refund_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user'], name='main_refund_user_id_06eaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='main_refund_order_i_e35acf_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['method'], name='main_refund_method_80ffa3_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='main_refund_status_82d14d_idx'),
        ),
    ]
