# Generated by Django 5.1.6 on 2025-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('payment', 'پرداخت'), ('refund', 'بازپرداخت')], default='deposit', max_length=20, verbose_name='Type'),
        ),
    ]
