# Generated by Django 5.1.6 on 2025-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='default', max_length=50, unique=True, verbose_name='Reference ID'),
        ),
    ]
