# Generated by Django 5.1.6 on 2025-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Reference ID'),
        ),
    ]
