# Generated by Django 5.1.6 on 2025-11-14 09:13

import config.storages
import django.db.models.deletion
import utilities.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_transaction_type'),
        ('users', '0004_remove_payment_is_sucessful_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={},
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reason',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_hold', 'در-انتظار-ثبت'), ('waiting', 'در-انتظار-پرداخت'), ('successful', 'پرداخت-موفق'), ('shipped', 'ارسال-شده'), ('completed', 'سفارش-تکمیل-شده'), ('canceled', 'سفارش-لغو-شده'), ('refunded', 'بازپرداخت-شده')], default='on_hold', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='main.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'درخواست-شده'), ('approved', 'تایید-شده'), ('rejected', 'رد-شده'), ('completed', 'تکمیل-شده')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='users.wallet', verbose_name='Wallet'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(verbose_name='Scheduled Time')),
                ('status', models.CharField(choices=[('scheduled', 'مشخص-شده'), ('picked_up', 'تحویل-داده-شده'), ('inspected', 'بررسی-شده'), ('approved', 'تایید-شده'), ('rejected', 'رد-شده')], default='scheduled', max_length=20, verbose_name='Status')),
                ('initial_check_passed', models.BooleanField(default=False, verbose_name='Initial Photo Check')),
                ('inspection_passed', models.BooleanField(default=False, verbose_name='Inspection Passed')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('request_image', models.ImageField(storage=config.storages.ArvanCloudStorage(), upload_to=utilities.media_utils.upload_to, verbose_name='Request Image')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Pickedup At')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='Inspected At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReturnRequest_orders', to='main.order', verbose_name='Order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='main_return_order_i_bc1cd6_idx'), models.Index(fields=['status'], name='main_return_status_ac86ec_idx'), models.Index(fields=['inspection_passed'], name='main_return_inspect_500dda_idx')],
            },
        ),
    ]
