# Generated by Django 5.1.6 on 2025-11-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Balance')),
                ('currency', models.CharField(default='IRR', max_length=10, verbose_name='Currency')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('frozen', 'مسدود'), ('closed', 'بسته\u200c-شده')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Wallet Owner')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'indexes': [models.Index(fields=['owner'], name='users_walle_owner_i_9d067c_idx'), models.Index(fields=['status'], name='users_walle_status_bbef00_idx')],
            },
        ),
    ]
