# Generated by Django 5.1.6 on 2025-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_active',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_available',
            field=models.BooleanField(default=True, editable=False, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('sent_back', 'Sent Back'), ('defective', 'Defective')], max_length=10, verbose_name='Warehouse Type'),
        ),
    ]
