# Generated by Django 5.1.6 on 2025-04-05 06:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_warehouse_is_active_warehouse_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Applied'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('defective', 'Defective'), ('sent_back', 'Sent Back')], default='input', max_length=10, verbose_name='Warehouse Type'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_wishlist_item'),
        ),
    ]
