# Generated by Django 5.1.6 on 2025-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cartitem_status_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('input', 'ورودی'), ('output', 'خروجی'), ('defective', 'مرجوعی'), ('sent_back', 'مرجوع-شده')], default='input', max_length=10, verbose_name='Warehouse Type'),
        ),
    ]
