# Generated by Django 5.1.6 on 2025-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
