# Generated by Django 5.1.6 on 2025-11-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='day',
            field=models.CharField(max_length=10, verbose_name='Day of the Week'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.deliveryschedule', verbose_name='Delivery Schedule'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('processed', 'پردازش-شده'), ('abandoned', 'لغو-شده')], default='active', max_length=10, verbose_name='Cart Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Cost/Sell Price'),
        ),
    ]
