# Generated by Django 5.1.6 on 2025-11-10 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deliveryschedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deliveryschedule', verbose_name='Delivery Schedule'),
        ),
    ]
