# Generated by Django 5.1.6 on 2025-11-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_delivery_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('processed', 'پردازش-شده'), ('abandoned', 'لغو-شده')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
