# Generated by Django 5.1.6 on 2025-04-14 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_amount_payable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userview',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userview',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userview',
            name='view_count',
            field=models.PositiveIntegerField(default=1, verbose_name='View Count'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['max_usage'], name='main_coupon_max_usa_3bb9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['usage_count'], name='main_coupon_usage_c_f6218d_idx'),
        ),
    ]
