# Generated by Django 5.1.6 on 2025-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_discount_applied_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='TEMP-000000', editable=False, max_length=20, unique=True, verbose_name='Order Number'),
        ),
    ]
