# Generated by Django 5.1.6 on 2025-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_userview_timestamp_userview_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Payment ID'),
        ),
    ]
