# Generated by Django 5.1.6 on 2025-05-15 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_transaction_payment_id'),
        ('users', '0002_remove_payment_users_payme_payment_e0854e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processed', 'Processed')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processed', 'Processed'), ('abandoned', 'Abandoned')], default='active', max_length=10, verbose_name='Cart Status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Cost Price'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['status'], name='main_shoppi_status_118306_idx'),
        ),
    ]
