# Generated by Django 5.1.6 on 2025-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cartitem_status_shoppingcart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='time',
            field=models.CharField(choices=[('8_10', '8 - 10'), ('10_12', '10 - 12'), ('12_14', '12 - 14'), ('14_16', '14 - 16'), ('16_18', '16 - 18'), ('18_20', '18 - 20'), ('20_22', '20 - 22')], error_messages={'invalid_choice': 'زمان انتخاب شده در لیست بازه\u200cهای مجاز نیست، لطفا زمان معتبری وارد کنید.'}, max_length=10, verbose_name='Time'),
        ),
    ]
