# Generated by Django 5.1.6 on 2025-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_deliveryschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shipped At'),
        ),
    ]
