# Generated by Django 5.1.6 on 2025-11-11 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_transaction_reference_id'),
        ('users', '0004_remove_payment_is_sucessful_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refund',
            name='main_refund_user_id_06eaf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='main_transa_user_id_553a48_idx',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='refund',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Refund_wallet', to='users.wallet', verbose_name='Wallet'),
        ),
    ]
