# Generated by Django 5.1.6 on 2025-11-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_refund_main_refund_user_id_06eaf2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('payment', 'پرداخت'), ('deposit', 'واریز'), ('refund', 'بازپرداخت')], default='payment', max_length=20, verbose_name='Type'),
        ),
    ]
